-- member_ecosystem 데이터 (11 rows)

INSERT INTO member_ecosystem (rank, name_ko, name_en, unit, clip_count, total_clip_views, avg_clip_views, fan_channels, top_clip, top_clip_views, top_channel) VALUES (1, '텐코 시부키', 'Tenko Shibuki', 'CLICHE', 25, 5349552, 213982.1, 16, '용사와 여우신이 부르는 거북이｜Davichi(다비치)_Turtle(거북이) Live Cover.텐코 시부키 X 유즈하 리코', 1731333, '서트 클립 Surt Clip');
INSERT INTO member_ecosystem (rank, name_ko, name_en, unit, clip_count, total_clip_views, avg_clip_views, fan_channels, top_clip, top_clip_views, top_channel) VALUES (2, '강지', 'Kangji', 'STELLIVE', 10, 3838772, 383877.2, 4, '??? : 자기야 나 방송 끝났어~  #스텔라이브 #버튜버', 2309536, '클립따는 유인원');
INSERT INTO member_ecosystem (rank, name_ko, name_en, unit, clip_count, total_clip_views, avg_clip_views, fan_channels, top_clip, top_clip_views, top_channel) VALUES (3, '네네코 마시로', 'Neneko Mashiro', 'UNIVERSE', 51, 3254565, 63815.0, 16, '하이요 얼굴 공개 ㄷㄷ', 1024896, 'Hot Clip');
INSERT INTO member_ecosystem (rank, name_ko, name_en, unit, clip_count, total_clip_views, avg_clip_views, fan_channels, top_clip, top_clip_views, top_channel) VALUES (4, '아카네 리제', 'Akane Lize', 'UNIVERSE', 24, 2898784, 120782.7, 8, '리제의 &#39;그 클립&#39; 을 본 부키 ㅋㅋㅋㅋ', 793628, '누따비');
INSERT INTO member_ecosystem (rank, name_ko, name_en, unit, clip_count, total_clip_views, avg_clip_views, fan_channels, top_clip, top_clip_views, top_channel) VALUES (5, '아야츠노 유니', 'Ayatsuno Yuni', 'EVERYS', 35, 2871015, 82029.0, 17, '말 실수한 유니 #shorts #유니 #아야츠노유니', 1050808, '이로이로_키리누키');
INSERT INTO member_ecosystem (rank, name_ko, name_en, unit, clip_count, total_clip_views, avg_clip_views, fan_channels, top_clip, top_clip_views, top_channel) VALUES (6, '하나코 나나', 'Hanako Nana', 'CLICHE', 29, 1534719, 52921.3, 18, '그 클립을 보고 히나에게 벽을 느껴버린 나나', 391614, '스텔클립클립');
INSERT INTO member_ecosystem (rank, name_ko, name_en, unit, clip_count, total_clip_views, avg_clip_views, fan_channels, top_clip, top_clip_views, top_channel) VALUES (7, '아라하시 타비', 'Arahashi Tabi', 'UNIVERSE', 41, 1529103, 37295.2, 10, '힘드신군뇨 #shorts #하나코나나 #스텔라이브 #키리누키', 526424, '누키누끼');
INSERT INTO member_ecosystem (rank, name_ko, name_en, unit, clip_count, total_clip_views, avg_clip_views, fan_channels, top_clip, top_clip_views, top_channel) VALUES (8, '시라유키 히나', 'Shirayuki Hina', 'UNIVERSE', 27, 1295443, 47979.4, 11, '검은색임 내가봤어 #vtuber #shorts #STELLIVE #버튜버 #히나', 466413, 'FTECLIP');
INSERT INTO member_ecosystem (rank, name_ko, name_en, unit, clip_count, total_clip_views, avg_clip_views, fan_channels, top_clip, top_clip_views, top_channel) VALUES (9, '유즈하 리코', 'Yuzuha Riko', 'CLICHE', 29, 1254868, 43271.3, 12, '리코 테트리스 시참 연습 중 (당시기준)테트리오 한국 1위가 들어온 건에 대하여 [유즈하 리코 클립]', 183323, '스텔나스_팬채널');
INSERT INTO member_ecosystem (rank, name_ko, name_en, unit, clip_count, total_clip_views, avg_clip_views, fan_channels, top_clip, top_clip_views, top_channel) VALUES (10, '아오쿠모 린', 'Aokumo Rin', 'CLICHE', 10, 632772, 63277.2, 5, '[린 클립] 수능 영어 지문 보고 헛구역질 하는 린', 256088, '피엔나 소세지');
INSERT INTO member_ecosystem (rank, name_ko, name_en, unit, clip_count, total_clip_views, avg_clip_views, fan_channels, top_clip, top_clip_views, top_channel) VALUES (11, '사키하네 후야', 'Sakihane Huya', 'EVERYS', 25, 71076, 2843.0, 3, '【咲羽 風夜】日本語の画期的な秘密に気づいて興奮するフヤさん【ステライブ切り抜き/日韓字幕】', 16560, 'すてら日和');
