-- member_ecosystem 데이터 (10 rows)

INSERT INTO member_ecosystem (rank, name_ko, name_en, unit, clip_count, total_clip_views, avg_clip_views, fan_channels, top_clip, top_clip_views, top_channel) VALUES (1, '텐코 시부키', 'Tenko Shibuki', 'CLICHE', 21, 5181520, 246739.0, 14, '용사와 여우신이 부르는 거북이｜Davichi(다비치)_Turtle(거북이) Live Cover.텐코 시부키 X 유즈하 리코', 1780568, '서트 클립 Surt Clip');
INSERT INTO member_ecosystem (rank, name_ko, name_en, unit, clip_count, total_clip_views, avg_clip_views, fan_channels, top_clip, top_clip_views, top_channel) VALUES (2, '시라유키 히나', 'Shirayuki Hina', 'UNIVERSE', 30, 2640011, 88000.4, 19, 'とばっちりを受けたのは…｜#嘆きの亡霊 4話 #切り抜き  #shorts  #アニメ #anime', 595018, 'GREE Entertainment ANIME & GAME【公式】');
INSERT INTO member_ecosystem (rank, name_ko, name_en, unit, clip_count, total_clip_views, avg_clip_views, fan_channels, top_clip, top_clip_views, top_channel) VALUES (3, '아야츠노 유니', 'Ayatsuno Yuni', 'EVERYS', 28, 2327358, 83119.9, 13, '말 실수한 유니 #shorts #유니 #아야츠노유니', 1068374, '이로이로_키리누키');
INSERT INTO member_ecosystem (rank, name_ko, name_en, unit, clip_count, total_clip_views, avg_clip_views, fan_channels, top_clip, top_clip_views, top_channel) VALUES (4, '아카네 리제', 'Akane Lize', 'UNIVERSE', 23, 2161274, 93968.4, 9, '아카네 리제 - 抜錨(출항/발묘) Live Cover', 750155, '피엔나야 클립따줘');
INSERT INTO member_ecosystem (rank, name_ko, name_en, unit, clip_count, total_clip_views, avg_clip_views, fan_channels, top_clip, top_clip_views, top_channel) VALUES (5, '네네코 마시로', 'Neneko Mashiro', 'UNIVERSE', 43, 2034544, 47315.0, 12, '서러움에 결국 울음이 터져버린 시로...', 443398, '서트 클립 Surt Clip');
INSERT INTO member_ecosystem (rank, name_ko, name_en, unit, clip_count, total_clip_views, avg_clip_views, fan_channels, top_clip, top_clip_views, top_channel) VALUES (6, '아라하시 타비', 'Arahashi Tabi', 'UNIVERSE', 43, 1200928, 27928.6, 12, 'タビの顔が変顔になり爆笑したり、つなが本物の猫ではなく自称猫だったことに衝撃を受けるタビ【猫汰つな/荒波子タビ/ぶいすぽ切り抜き/リアルコラボ/日本語翻訳】', 225602, 'ぶいすぽ推し活 / バタフライ[切り抜き]');
INSERT INTO member_ecosystem (rank, name_ko, name_en, unit, clip_count, total_clip_views, avg_clip_views, fan_channels, top_clip, top_clip_views, top_channel) VALUES (7, '하나코 나나', 'Hanako Nana', 'CLICHE', 17, 983404, 57847.3, 11, '그 클립을 보고 히나에게 벽을 느껴버린 나나', 470509, '스텔클립클립');
INSERT INTO member_ecosystem (rank, name_ko, name_en, unit, clip_count, total_clip_views, avg_clip_views, fan_channels, top_clip, top_clip_views, top_channel) VALUES (8, '아오쿠모 린', 'Aokumo Rin', 'CLICHE', 6, 492743, 82123.8, 3, '[린 클립] 수능 영어 지문 보고 헛구역질 하는 린', 260848, '피엔나 소세지');
INSERT INTO member_ecosystem (rank, name_ko, name_en, unit, clip_count, total_clip_views, avg_clip_views, fan_channels, top_clip, top_clip_views, top_channel) VALUES (9, '유즈하 리코', 'Yuzuha Riko', 'CLICHE', 6, 373909, 62318.2, 5, '【総勢11名】レジェンドVtuberが大量に現れてしまうろあちゃんの１周年逆凸まとめ【海月雲ろあ/雨海ルカ/結城さくな/kson/切り抜き】', 196613, 'くらげう工房');
INSERT INTO member_ecosystem (rank, name_ko, name_en, unit, clip_count, total_clip_views, avg_clip_views, fan_channels, top_clip, top_clip_views, top_channel) VALUES (10, '사키하네 후야', 'Sakihane Huya', 'EVERYS', 28, 91984, 3285.1, 4, '【咲羽 風夜】日本語の画期的な秘密に気づいて興奮するフヤさん【ステライブ切り抜き/日韓字幕】', 16711, 'すてら日和');
