-- member_ecosystem 데이터 (9 rows)

INSERT INTO member_ecosystem (rank, name_ko, name_en, unit, clip_count, total_clip_views, avg_clip_views, fan_channels, top_clip, top_clip_views, top_channel) VALUES (1, '텐코 시부키', 'Tenko Shibuki', 'CLICHE', 25, 5375971, 215038.8, 15, '용사와 여우신이 부르는 거북이｜Davichi(다비치)_Turtle(거북이) Live Cover.텐코 시부키 X 유즈하 리코', 1784123, '서트 클립 Surt Clip');
INSERT INTO member_ecosystem (rank, name_ko, name_en, unit, clip_count, total_clip_views, avg_clip_views, fan_channels, top_clip, top_clip_views, top_channel) VALUES (2, '아야츠노 유니', 'Ayatsuno Yuni', 'EVERYS', 38, 3214070, 84580.8, 19, '말 실수한 유니 #shorts #유니 #아야츠노유니', 1069174, '이로이로_키리누키');
INSERT INTO member_ecosystem (rank, name_ko, name_en, unit, clip_count, total_clip_views, avg_clip_views, fan_channels, top_clip, top_clip_views, top_channel) VALUES (3, '시라유키 히나', 'Shirayuki Hina', 'UNIVERSE', 27, 3110881, 115217.8, 13, 'とばっちりを受けたのは…｜#嘆きの亡霊 4話 #切り抜き  #shorts  #アニメ #anime', 595195, 'GREE Entertainment ANIME & GAME【公式】');
INSERT INTO member_ecosystem (rank, name_ko, name_en, unit, clip_count, total_clip_views, avg_clip_views, fan_channels, top_clip, top_clip_views, top_channel) VALUES (4, '아카네 리제', 'Akane Lize', 'UNIVERSE', 26, 2458268, 94548.8, 9, '아카네 리제 - 抜錨(출항/발묘) Live Cover', 760488, '피엔나야 클립따줘');
INSERT INTO member_ecosystem (rank, name_ko, name_en, unit, clip_count, total_clip_views, avg_clip_views, fan_channels, top_clip, top_clip_views, top_channel) VALUES (5, '네네코 마시로', 'Neneko Mashiro', 'UNIVERSE', 45, 2284053, 50756.7, 14, '서러움에 결국 울음이 터져버린 시로...', 444080, '서트 클립 Surt Clip');
INSERT INTO member_ecosystem (rank, name_ko, name_en, unit, clip_count, total_clip_views, avg_clip_views, fan_channels, top_clip, top_clip_views, top_channel) VALUES (6, '유즈하 리코', 'Yuzuha Riko', 'CLICHE', 26, 1388608, 53408.0, 13, '리코 테트리스 시참 연습 중 (당시기준)테트리오 한국 1위가 들어온 건에 대하여 [유즈하 리코 클립]', 246817, '스텔나스_팬채널');
INSERT INTO member_ecosystem (rank, name_ko, name_en, unit, clip_count, total_clip_views, avg_clip_views, fan_channels, top_clip, top_clip_views, top_channel) VALUES (7, '아라하시 타비', 'Arahashi Tabi', 'UNIVERSE', 33, 1053023, 31909.8, 11, 'タビの顔が変顔になり爆笑したり、つなが本物の猫ではなく自称猫だったことに衝撃を受けるタビ【猫汰つな/荒波子タビ/ぶいすぽ切り抜き/リアルコラボ/日本語翻訳】', 225990, 'ぶいすぽ推し活 / バタフライ[切り抜き]');
INSERT INTO member_ecosystem (rank, name_ko, name_en, unit, clip_count, total_clip_views, avg_clip_views, fan_channels, top_clip, top_clip_views, top_channel) VALUES (8, '아오쿠모 린', 'Aokumo Rin', 'CLICHE', 6, 493487, 82247.8, 3, '[린 클립] 수능 영어 지문 보고 헛구역질 하는 린', 261315, '피엔나 소세지');
INSERT INTO member_ecosystem (rank, name_ko, name_en, unit, clip_count, total_clip_views, avg_clip_views, fan_channels, top_clip, top_clip_views, top_channel) VALUES (9, '하나코 나나', 'Hanako Nana', 'CLICHE', 12, 384785, 32065.4, 7, 'ななたまロングトーン【珠乃井ナナ/切り抜き】', 135367, 'ろこびっと【珠乃井ナナ切り抜き】');
