-- corp_search 데이터 (9 rows)

INSERT INTO corp_search (query, label, category, context, matched, n_candidates, corp_code, corp_name, corp_eng_name, stock_code, note) VALUES ('스텔라이브', '스텔라이브 (StelLive 운영법인)', '핵심', '브랜드명·법인명(주식회사 스텔라이브, 2023.4 설립, 언론 보도 기준) 둘 다 검색.', False, 0, NULL, NULL, NULL, NULL, 'DART 기업코드 마스터에 없음(비상장·소규모 외부감사 미제출 또는 국내 미등록 가능)');
INSERT INTO corp_search (query, label, category, context, matched, n_candidates, corp_code, corp_name, corp_eng_name, stock_code, note) VALUES ('브레이브그룹코리아', '브레이브그룹코리아 (Brave group 한국법인)', '핵심', '2025.7 인수 발표 시 설립 보도된 한국 자회사명.', False, 0, NULL, NULL, NULL, NULL, 'DART 기업코드 마스터에 없음(비상장·소규모 외부감사 미제출 또는 국내 미등록 가능)');
INSERT INTO corp_search (query, label, category, context, matched, n_candidates, corp_code, corp_name, corp_eng_name, stock_code, note) VALUES ('브레이브그룹', 'Brave group (일본 모기업)', '핵심', '일본 법인. 한국 DART는 내국 신고의무자만 다루므로 원칙적으로 대상 아님 — 확인용.', False, 0, NULL, NULL, NULL, NULL, 'DART 기업코드 마스터에 없음(비상장·소규모 외부감사 미제출 또는 국내 미등록 가능)');
INSERT INTO corp_search (query, label, category, context, matched, n_candidates, corp_code, corp_name, corp_eng_name, stock_code, note) VALUES ('팬딩', '팬딩 (Fanding, 팬 커머스)', '비교군', 'PRD Phase2 11번(팬 커머스) 대상. (주)팬딩, 2018.9 설립.', True, 1, '01921913', '팬딩', 'Fanding Inc.', NULL, '완전 일치 1건');
INSERT INTO corp_search (query, label, category, context, matched, n_candidates, corp_code, corp_name, corp_eng_name, stock_code, note) VALUES ('샌드박스네트워크', '샌드박스네트워크 (국내 대형 MCN)', '비교군', '국내 최대급 MCN·크리에이터 매니지먼트. 규모 비교용.', True, 1, '01375682', '샌드박스네트워크', 'Sandbox Network Inc.', NULL, '완전 일치 1건');
INSERT INTO corp_search (query, label, category, context, matched, n_candidates, corp_code, corp_name, corp_eng_name, stock_code, note) VALUES ('패러블엔터테인먼트', '패러블엔터테인먼트 (이세계아이돌 소속사)', '비교군', '이세계아이돌(우왁굳/왁타버스) 실제 관리사 — 언론 보도 기준, DART 서류 자체에 표기 없음.', True, 1, '01906622', '패러블엔터테인먼트', 'PARABLE ENTERTAINMENT Inc', NULL, '완전 일치 1건');
INSERT INTO corp_search (query, label, category, context, matched, n_candidates, corp_code, corp_name, corp_eng_name, stock_code, note) VALUES ('브레이브엔터테인먼트', '브레이브엔터테인먼트 (참고: 동명이인 주의)', '동명이인', 'K-pop 걸그룹 ''브레이브걸스'' 소속사. VTuber Brave group과 무관 — 혼동 방지용으로만 기록.', True, 1, '01605556', '브레이브엔터테인먼트', 'BRAVE ENTERTAINMENT', NULL, '완전 일치 1건');
INSERT INTO corp_search (query, label, category, context, matched, n_candidates, corp_code, corp_name, corp_eng_name, stock_code, note) VALUES ('SOOP', 'SOOP (구 아프리카TV, 치지직 경쟁 플랫폼)', '플랫폼', '상장사(067160). 국내 라이브 스트리밍 플랫폼 비교군.', True, 1, '00399694', 'SOOP', 'SOOP CO., LTD.', '067160', '완전 일치 1건');
INSERT INTO corp_search (query, label, category, context, matched, n_candidates, corp_code, corp_name, corp_eng_name, stock_code, note) VALUES ('NAVER', 'NAVER (치지직 운영사)', '플랫폼', '상장사(035420). 프로젝트3·8이 다루는 치지직의 모기업.', True, 1, '00266961', 'NAVER', 'NAVER Corporation', '035420', '완전 일치 1건');
