-- fanding_tiers 데이터 (67 rows)

INSERT INTO fanding_tiers (creator_url, nickname, tier_index, tier_title, price_krw) VALUES ('myjZVWA2LSO4', '유키링 yukilling', 0, '키링이 환생 도와주기', 45000);
INSERT INTO fanding_tiers (creator_url, nickname, tier_index, tier_title, price_krw) VALUES ('hananeno_chuchu', '하나네노 츄츄', 0, '츄츄와 DM 멤버십', 3700);
INSERT INTO fanding_tiers (creator_url, nickname, tier_index, tier_title, price_krw) VALUES ('LNFyxMaszUEC', '빅터 KR', 0, '소량 투자', 1000);
INSERT INTO fanding_tiers (creator_url, nickname, tier_index, tier_title, price_krw) VALUES ('LNFyxMaszUEC', '빅터 KR', 1, '기본 투자', 10000);
INSERT INTO fanding_tiers (creator_url, nickname, tier_index, tier_title, price_krw) VALUES ('LNFyxMaszUEC', '빅터 KR', 2, '대형 투자', 100000);
INSERT INTO fanding_tiers (creator_url, nickname, tier_index, tier_title, price_krw) VALUES ('hika1', '히카1', 0, '기본', 1000);
INSERT INTO fanding_tiers (creator_url, nickname, tier_index, tier_title, price_krw) VALUES ('TWILLITSTUDIO_', 'TWILLITSTUDIO_트윌릿', 0, 'WILLIT', 1000);
INSERT INTO fanding_tiers (creator_url, nickname, tier_index, tier_title, price_krw) VALUES ('cihe_', '인텔리 치에', 0, '치유사', 5000);
INSERT INTO fanding_tiers (creator_url, nickname, tier_index, tier_title, price_krw) VALUES ('cihe_', '인텔리 치에', 1, '특별치유사', 10000);
INSERT INTO fanding_tiers (creator_url, nickname, tier_index, tier_title, price_krw) VALUES ('studiosegno', '스튜디오 세뇨', 0, '스튜디오 세뇨 멤버십 [달세뇨] 1기', 22000);
INSERT INTO fanding_tiers (creator_url, nickname, tier_index, tier_title, price_krw) VALUES ('CHOOSE', '츄즈', 0, '💚츄즈 구독💚', 1000);
INSERT INTO fanding_tiers (creator_url, nickname, tier_index, tier_title, price_krw) VALUES ('VDePEsT5SZIr', '아쿠쨩', 0, '아쿠마단', 1000);
INSERT INTO fanding_tiers (creator_url, nickname, tier_index, tier_title, price_krw) VALUES ('chuing', '김츄잉', 0, '츄잉이의 다이아방', 7200);
INSERT INTO fanding_tiers (creator_url, nickname, tier_index, tier_title, price_krw) VALUES ('LJzftS8Mmcgl', '배부른 강아지 527841', 0, '기본 멤버쉽', 2000);
INSERT INTO fanding_tiers (creator_url, nickname, tier_index, tier_title, price_krw) VALUES ('02rKIyDJSxjd', '모모시로 카나', 0, '코야미쿤', 1000);
INSERT INTO fanding_tiers (creator_url, nickname, tier_index, tier_title, price_krw) VALUES ('jKn2OagAoQ4Y', '마리엘', 0, '쭉냥이 멤버십', 55000);
INSERT INTO fanding_tiers (creator_url, nickname, tier_index, tier_title, price_krw) VALUES ('iotayona', '요나 Yona', 0, '일각모비🐳', 8690);
INSERT INTO fanding_tiers (creator_url, nickname, tier_index, tier_title, price_krw) VALUES ('iotayona', '요나 Yona', 1, '💎크리스탈 일각모비🐳', 27500);
INSERT INTO fanding_tiers (creator_url, nickname, tier_index, tier_title, price_krw) VALUES ('visoe', '이소에', 0, '소에월드', 5500);
INSERT INTO fanding_tiers (creator_url, nickname, tier_index, tier_title, price_krw) VALUES ('pgtQf3VFG0nO', '유루리 Yururi', 0, '파랑새 보호 협회', 3630);
INSERT INTO fanding_tiers (creator_url, nickname, tier_index, tier_title, price_krw) VALUES ('maya100', '마야100', 0, '일반 멤버십', 6600);
INSERT INTO fanding_tiers (creator_url, nickname, tier_index, tier_title, price_krw) VALUES ('maya100', '마야100', 1, '다이아 멤버십', 55000);
INSERT INTO fanding_tiers (creator_url, nickname, tier_index, tier_title, price_krw) VALUES ('Reana', '레아나 Reana', 0, '레아나 팬딩', 1100);
INSERT INTO fanding_tiers (creator_url, nickname, tier_index, tier_title, price_krw) VALUES ('alicemana', '아리스마나', 0, '휴일의 여우불', 30000);
INSERT INTO fanding_tiers (creator_url, nickname, tier_index, tier_title, price_krw) VALUES ('shiroko', '시로코 SHIROKO', 0, '타마시', 3300);
INSERT INTO fanding_tiers (creator_url, nickname, tier_index, tier_title, price_krw) VALUES ('moonmomo', '문모모', 0, '곰탕이', 5500);
INSERT INTO fanding_tiers (creator_url, nickname, tier_index, tier_title, price_krw) VALUES ('forthemore', '포더모어 ForTheMore', 0, '⚡ 포더모어 포도알 멤버십 2기', 29000);
INSERT INTO fanding_tiers (creator_url, nickname, tier_index, tier_title, price_krw) VALUES ('quLa8SzFA0Db', '모야__', 0, '모야모야?', 11000);
INSERT INTO fanding_tiers (creator_url, nickname, tier_index, tier_title, price_krw) VALUES ('watame_plan_kr', '와타메이트 기획부 KR', 0, '와타메이트', 1100);
INSERT INTO fanding_tiers (creator_url, nickname, tier_index, tier_title, price_krw) VALUES ('MEv9NGSudtL8', '정나은양', 0, '아이언 멤버십', 5500);
INSERT INTO fanding_tiers (creator_url, nickname, tier_index, tier_title, price_krw) VALUES ('hareu', '하르-', 0, '하르 멤버십', 11000);
INSERT INTO fanding_tiers (creator_url, nickname, tier_index, tier_title, price_krw) VALUES ('Ux35RL4tPZJY', '아티손즈', 0, '테스트 (구매하지 말아주세요)', 1100);
INSERT INTO fanding_tiers (creator_url, nickname, tier_index, tier_title, price_krw) VALUES ('kg0qIswfj4Vr', '아랭 ARENG', 0, '성수기', 10890);
INSERT INTO fanding_tiers (creator_url, nickname, tier_index, tier_title, price_krw) VALUES ('kg0qIswfj4Vr', '아랭 ARENG', 1, '마스터 성수기', 550000);
INSERT INTO fanding_tiers (creator_url, nickname, tier_index, tier_title, price_krw) VALUES ('heemi', '희미', 0, 'HP', 3300);
INSERT INTO fanding_tiers (creator_url, nickname, tier_index, tier_title, price_krw) VALUES ('vTSF8M3yYcBf', '찬비니', 0, '찬빈이에게 후원', 16500);
INSERT INTO fanding_tiers (creator_url, nickname, tier_index, tier_title, price_krw) VALUES ('1Ko0Wup6L2wV', '원사비', 0, '반짝이는 방울이', 1100);
INSERT INTO fanding_tiers (creator_url, nickname, tier_index, tier_title, price_krw) VALUES ('jongtachi', '종타치', 0, '브론즈', 1100);
INSERT INTO fanding_tiers (creator_url, nickname, tier_index, tier_title, price_krw) VALUES ('STARDAYS', '스타데이즈', 0, '스타데이즈 멤버십 플랜 \"별사탕\" 1기', 24000);
INSERT INTO fanding_tiers (creator_url, nickname, tier_index, tier_title, price_krw) VALUES ('aho0226', '아호_aho', 0, '아호 사랑둥이', 11000);
INSERT INTO fanding_tiers (creator_url, nickname, tier_index, tier_title, price_krw) VALUES ('WR9TP4OQqLM8', '아카이브 스튜디오', 0, '싱글 멤버쉽', 5390);
INSERT INTO fanding_tiers (creator_url, nickname, tier_index, tier_title, price_krw) VALUES ('imducko3o', '오리꿍_Fanding', 0, '오리꿍 멤버십', 11000);
INSERT INTO fanding_tiers (creator_url, nickname, tier_index, tier_title, price_krw) VALUES ('hiyoko', '히요코_POCOTONE', 0, '히요코 멤버십', 11000);
INSERT INTO fanding_tiers (creator_url, nickname, tier_index, tier_title, price_krw) VALUES ('dalchesom', 'Dalchesom', 0, '달체솜 멤버십', 11000);
INSERT INTO fanding_tiers (creator_url, nickname, tier_index, tier_title, price_krw) VALUES ('vunet', '유네트', 0, '모험가 멤버십', 5500);
INSERT INTO fanding_tiers (creator_url, nickname, tier_index, tier_title, price_krw) VALUES ('rev_vit', '레브 Rev_', 0, '의뢰소 견학', 7700);
INSERT INTO fanding_tiers (creator_url, nickname, tier_index, tier_title, price_krw) VALUES ('Y1Y4_', '이야', 0, '숲 속 아리단🐤', 11000);
INSERT INTO fanding_tiers (creator_url, nickname, tier_index, tier_title, price_krw) VALUES ('t95BmlTKSD7s', '죠셉죠슈아', 0, '사원단', 1100);
INSERT INTO fanding_tiers (creator_url, nickname, tier_index, tier_title, price_krw) VALUES ('Myong', '묭이', 0, '보물상자 엿보기', 8800);
INSERT INTO fanding_tiers (creator_url, nickname, tier_index, tier_title, price_krw) VALUES ('Myong', '묭이', 1, '보물상자 점령하기', 17600);
INSERT INTO fanding_tiers (creator_url, nickname, tier_index, tier_title, price_krw) VALUES ('HFVLRpcanjz1', '미베_', 0, '젤리젤리 플랜', 11000);
INSERT INTO fanding_tiers (creator_url, nickname, tier_index, tier_title, price_krw) VALUES ('iPsXc7F1ldLn', '앰구', 0, '커미션 맞긴 일러스트 선공개!', 3300);
INSERT INTO fanding_tiers (creator_url, nickname, tier_index, tier_title, price_krw) VALUES ('J9ZrQ63sY4Ry', 'ning_gu', 0, '닝갱신', 11000);
INSERT INTO fanding_tiers (creator_url, nickname, tier_index, tier_title, price_krw) VALUES ('jBk9WO2adheJ', '코튼캔탑', 0, '커버곡 미리 듣기', 1100);
INSERT INTO fanding_tiers (creator_url, nickname, tier_index, tier_title, price_krw) VALUES ('cRZIuFf3Mq5p', '베아루', 0, '원석단', 1100);
INSERT INTO fanding_tiers (creator_url, nickname, tier_index, tier_title, price_krw) VALUES ('5Zs9QAdTFcxk', '연루나', 0, '미리보기', 11000);
INSERT INTO fanding_tiers (creator_url, nickname, tier_index, tier_title, price_krw) VALUES ('lVHeuU1MNncE', '2브임', 0, '집사단', 1100);
INSERT INTO fanding_tiers (creator_url, nickname, tier_index, tier_title, price_krw) VALUES ('vrecord', '브이레코드_VRECORD', 0, '엿보기 멤버십', 5500);
INSERT INTO fanding_tiers (creator_url, nickname, tier_index, tier_title, price_krw) VALUES ('WXSt8G3KxVno', '여름어름', 0, '어름쟝의 특별한 얼음', 1100);
INSERT INTO fanding_tiers (creator_url, nickname, tier_index, tier_title, price_krw) VALUES ('Veginning', 'VGG', 0, '테스트', 1100);
INSERT INTO fanding_tiers (creator_url, nickname, tier_index, tier_title, price_krw) VALUES ('camellia1225', '동백 camellia', 0, '🐣아가 동박새', 6490);
INSERT INTO fanding_tiers (creator_url, nickname, tier_index, tier_title, price_krw) VALUES ('camellia1225', '동백 camellia', 1, '🐥성숙한 동박새', 10890);
INSERT INTO fanding_tiers (creator_url, nickname, tier_index, tier_title, price_krw) VALUES ('_marimo', '_마리모0', 0, '심해마을 주민(한정 50명)', 16390);
INSERT INTO fanding_tiers (creator_url, nickname, tier_index, tier_title, price_krw) VALUES ('stellive', '스텔라이브', 0, '스텔라이브 공식 팬클럽 [파스텔] 6기', 24000);
INSERT INTO fanding_tiers (creator_url, nickname, tier_index, tier_title, price_krw) VALUES ('kavy2020', 'KAVY 카비', 0, '한 컵', 2200);
INSERT INTO fanding_tiers (creator_url, nickname, tier_index, tier_title, price_krw) VALUES ('kavy2020', 'KAVY 카비', 1, '두 컵', 11000);
INSERT INTO fanding_tiers (creator_url, nickname, tier_index, tier_title, price_krw) VALUES ('kavy2020', 'KAVY 카비', 2, '세 컵', 55000);
