-- sentiment_metrics 데이터 (10 rows)

INSERT INTO sentiment_metrics (rank, name_ko, name_en, unit, n_comments, positive_share, negative_share, neutral_share, sentiment_score, top_topic, avg_likes) VALUES (1, '네네코 마시로', 'Neneko Mashiro', 'UNIVERSE', 30, 0.933, 0.0, 0.067, 0.933, '방송내용·게임', 229.2);
INSERT INTO sentiment_metrics (rank, name_ko, name_en, unit, n_comments, positive_share, negative_share, neutral_share, sentiment_score, top_topic, avg_likes) VALUES (2, '유즈하 리코', 'Yuzuha Riko', 'CLICHE', 30, 0.933, 0.0, 0.067, 0.933, '방송내용·게임', 980.0);
INSERT INTO sentiment_metrics (rank, name_ko, name_en, unit, n_comments, positive_share, negative_share, neutral_share, sentiment_score, top_topic, avg_likes) VALUES (3, '하나코 나나', 'Hanako Nana', 'CLICHE', 30, 0.9, 0.0, 0.1, 0.9, '방송내용·게임', 336.2);
INSERT INTO sentiment_metrics (rank, name_ko, name_en, unit, n_comments, positive_share, negative_share, neutral_share, sentiment_score, top_topic, avg_likes) VALUES (4, '텐코 시부키', 'Tenko Shibuki', 'CLICHE', 30, 0.9, 0.0, 0.1, 0.9, '성격·개그', 620.3);
INSERT INTO sentiment_metrics (rank, name_ko, name_en, unit, n_comments, positive_share, negative_share, neutral_share, sentiment_score, top_topic, avg_likes) VALUES (5, '아카네 리제', 'Akane Lize', 'UNIVERSE', 30, 0.833, 0.0, 0.167, 0.833, '성격·개그', 815.5);
INSERT INTO sentiment_metrics (rank, name_ko, name_en, unit, n_comments, positive_share, negative_share, neutral_share, sentiment_score, top_topic, avg_likes) VALUES (6, '아라하시 타비', 'Arahashi Tabi', 'UNIVERSE', 30, 0.833, 0.0, 0.167, 0.833, '성격·개그', 614.3);
INSERT INTO sentiment_metrics (rank, name_ko, name_en, unit, n_comments, positive_share, negative_share, neutral_share, sentiment_score, top_topic, avg_likes) VALUES (7, '시라유키 히나', 'Shirayuki Hina', 'UNIVERSE', 30, 0.8, 0.0, 0.2, 0.8, '방송내용·게임', 384.2);
INSERT INTO sentiment_metrics (rank, name_ko, name_en, unit, n_comments, positive_share, negative_share, neutral_share, sentiment_score, top_topic, avg_likes) VALUES (8, '사키하네 후야', 'Sakihane Huya', 'EVERYS', 30, 0.767, 0.0, 0.233, 0.767, '성격·개그', 209.4);
INSERT INTO sentiment_metrics (rank, name_ko, name_en, unit, n_comments, positive_share, negative_share, neutral_share, sentiment_score, top_topic, avg_likes) VALUES (9, '아오쿠모 린', 'Aokumo Rin', 'CLICHE', 30, 0.633, 0.0, 0.367, 0.633, '목소리·노래', 426.9);
INSERT INTO sentiment_metrics (rank, name_ko, name_en, unit, n_comments, positive_share, negative_share, neutral_share, sentiment_score, top_topic, avg_likes) VALUES (10, '아야츠노 유니', 'Ayatsuno Yuni', 'EVERYS', 30, 0.5, 0.167, 0.333, 0.333, '기타', 346.5);
